# --- Localization dictionary for user-facing strings ---
LANG = {
    "success": "Success",
    "error": "Error",
    "no_row_selected": "No row selected.",
    "import_success": "Import Successful",
    "export_success": "Export Successful",
    "confirm": "Confirm",
    "info": "Info",
    "ready": "Ready.",
    "autosaved": "💾 Autosaved!",
    "clear_all_confirm": "Are you sure you want to clear all data? This action cannot be undone.",
    "unsaved_changes": "You have unsaved changes. Are you sure you want to exit?",
    "database_error": "Database Error",
    "could_not_save_db": "Could not save to database:",
    "could_not_load_db": "Could not load from database:",
    "could_not_save_profile": "Could not save profile data:",
    "could_not_load_profile": "Could not load profile data:",
    "data_saved_db": "Data saved to database.",
    "data_loaded_db": "Data loaded from database.",
    "profile_saved_db": "Profile graph data saved to database.",
    "profile_loaded_db": "Profile graph data loaded from database.",
    "no_db_found": "No database file found.",
    "load_data": "Load Data",
    "calculation_complete": "Calculation complete. The graph has been updated.",
    "unknown_method": "Unknown calculation method selected.",
    "first_rl_error": "First RL must be a valid number.",
    "no_data_calculate": "No data entered to calculate.",
    "input_validation_error": "Input Validation Error",
    "info_title": "Info",
    "export_error": "Export Error",
    "failed_export_csv": "Failed to export to CSV:",
    "failed_export_excel": "Failed to export to Excel:",
    "exported_csv": "Exported to CSV.",
    "exported_excel": "Exported to Excel.",
    "exported_graph": "Graph successfully exported to:",
    "failed_export_graph": "Failed to export graph:",
    "pdf_generation_error": "PDF Generation Error",
    "failed_pdf_report": "Failed to generate PDF report:",
    "pdf_report_success": "PDF report generated successfully at:",
    "import_error": "Import Error",
    "failed_import": "Failed to import data:",
    "import_preview": "Import Preview",
    "column_mapping": "Column Mapping",
    "data_preview": "Data Preview",
    "file_has_header": "File has a header row (first row will be skipped)",
    "import": "Import",
    "cancel": "Cancel",
    "read_error": "Read Error",
    "could_not_read_csv": "Could not read CSV file:",
    "mapping_error": "Mapping Error",
    "column_mapped_twice": "is mapped more than once.",
    "confirm_delete": "Confirm Delete",
    "delete_rows_confirm": "Are you sure you want to delete {count} row(s)?",
    "annotation": "Annotation",
    "enter_annotation_text": "Please enter text for the annotation.",
    "click_place_annotation": "Click on the graph to place the annotation...",
    "annotation_added": "Annotation added.",
    "confirm_clear_annotations": "Are you sure you want to remove all annotations?",
    "annotations_cleared": "Annotations cleared.",
    "no_data_analyze": "There is no graph data to analyze.",
    "input_error": "Input Error",
    "valid_design_level": "Please enter a valid number for the design level.",
    "cut_fill_complete": "Cut and fill analysis complete.",
    "zoom_reset": "Zoom reset.",
    "zoom_mode": "Zoom mode: Drag to zoom in. Right-click to reset.",
    "pan_mode": "Pan mode: Drag to move the graph.",
    "session_restore": "Restore Last Session",
    "session_found": "A previous session was found. Restore it?",
    "session_restore_error": "Session Restore Error",
    "could_not_restore_session": "Could not restore session:",
    "session_restored": "Session restored.",
    "open_csv": "Open CSV",
    "open_as_leveling": "Open '{file}' as Leveling CSV? (No = Profile CSV)",
    "open_db": "Open DB",
    "open_as_leveling_db": "Open '{file}' as Leveling DB? (No = Profile DB)",
    "unknown_file_type": "Unknown File Type",
    "cannot_open_file": "Cannot open file: {file}",
    "import_csv": "Import CSV",
    "import_as_leveling": "Import '{file}' as Leveling CSV? (No = Profile CSV)",
    "unsupported_file": "Unsupported File",
    "only_csv_db_drag": "Only CSV and DB files can be imported by drag-and-drop. Ignored: {file}",
    "export_to_excel": "Export to Excel",
    "export_which_table": "Export which table?",
    "results_table": "Results Table",
    "profile_table": "Profile Table",
    "column_error": "Column Error",
    "at_least_one_visible": "At least one column must be visible.",
    "apply": "Apply",
    "customize_columns": "Customize Columns",
    "settings_import_success": "Settings imported.",
    "settings_export_success": "Settings exported.",
    "settings_import_error": "Failed to import settings:",
    "settings_export_error": "Failed to export settings:",
    "welcome_title": "Welcome to Leveling & Graphing App!",
    "welcome": "Welcome!",
    "get_started": "Get Started!",
    "about_title": "About",
    "about_text": "Leveling & Graphing App v{version}\n\nA tool for survey leveling calculations and profile visualization.\n\nDeveloped by Conrad.\nSupport: levelingapp@example.com\nGitHub: https://github.com/conrad/leveling-graphing-app\n\n© 2024 Conrad. All rights reserved.",
    "help_title": "Help / Guide",
    "help_welcome": "Welcome to the Leveling & Graphing App!",
    "help_getting_started": "1. Getting Started",
    "help_enter_first_rl": "• Enter your first Reduced Level (RL) in the 'First RL' box.",
    "help_input_readings": "• Input your survey readings (BS, IS, FS) into the main table. The first reading must be a Backsight (BS).",
    "help_change_point": "• A Change Point (CP) is a row with both a BS and an FS reading.",
    "help_final_reading": "• The final reading must be a Foresight (FS).",
    "help_calculation": "2. Calculation",
    "help_choose_method": "• Choose a calculation method: Height of Instrument (HI) or Rise & Fall (RF).",
    "help_enter_last_rl": "• Enter the known 'Last RL' for an automatic misclosure and adjustment calculation.",
    "help_calculate_update": "• Click 'Calculate & Update Graph' to see the results and plot the profile.",
    "help_profile_graph": "3. The Profile Graph",
    "help_plot_rl": "• The graph plots your Adjusted RL against the Point/Distance.",
    "help_graph_controls": "• Use the controls to smooth the curve, show/hide markers, and add data labels.",
    "help_comparison_profile": "• Use 'File > Load Comparison Profile' to overlay a second profile on the graph.",
    "help_cut_fill": "• Analyze cut and fill volumes by entering a 'Design Level' and clicking 'Analyze'.",
    "help_data_management": "4. Data Management",
    "help_import_csv": "• Use 'File > Import' to load data from CSV files.",
    "help_save_db": "• Save your work to the local database using 'File > Save... to DB'.",
    "help_right_click": "• Right-click on tables for more options like Copy, Paste, and Delete.",
    "invalid_input": "Invalid input detected in {count} field(s).",
}

DATA_VALIDATION_RULES = """
Data Validation Rules:
- The first row must be a Backsight (BS) only.
- Only BS and FS can be present in a change point row (no IS).
- IS cannot be in the same row as BS or FS.
- Each row must have at least one valid reading (BS, IS, or FS).
- No negative or non-numeric readings.
- The last row must be an FS only (not BS or IS).
- For change points, both BS and FS must be present in the same row.
""" 